import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import { User } from '../models/User.js';
import { Vertical } from '../models/Vertical.js';
import { Settings } from '../models/Settings.js';
import { Attendance } from '../models/Attendance.js';
import { Event } from '../models/Event.js';
import { EmailLog } from '../models/EmailLog.js';
import { AuditLog } from '../models/AuditLog.js';
import { ROLES, DEFAULT_VERTICALS } from '../config/constants.js';
import { ENV } from '../config/env.js';

// All 183 members accurately extracted from the official PDF
export const PDF_RECORDS = [
  // Page 1 / 7 / 13
  {
    timestamp: '9-18-2026 12:19:16',
    email: 'venkatasainadh2008@gmail.com',
    name: 'Venkata Sai Nadh Chalamala',
    regNo: '251FK01021',
    branch: 'BBA',
    year: 'II',
    gender: 'Male',
    phone: '9014587441',
    vertical: 'Marketing',
    position: 'Co-ordinator',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:20:02',
    email: 'afrozashaik5412@gmail.com',
    name: 'Shaik Kowsar Moin',
    regNo: '231FA14087',
    branch: 'Biotechnology',
    year: 'IV',
    gender: 'Female',
    phone: '7842613338',
    vertical: 'Marketing',
    position: 'Co-ordinator',
    linkedin: 'https://www.linkedin.com/in/kowsar-moin-shaik-071a8331a',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:31:11',
    email: 'harshinimulpuri@gmail.com',
    name: 'M harshini',
    regNo: '261FA15021',
    branch: 'Food technology',
    year: 'I',
    gender: 'Female',
    phone: '8688464138',
    vertical: 'Corporate Communication',
    position: 'Co-ordinator',
    linkedin: 'https://www.linkedin.com/in/harshini-mulpuri-393a493b8',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:35:11',
    email: 'vfstr.241fa04a59@gmail.com',
    name: 'D.Chethana Laxmi',
    regNo: '241FA04A59',
    branch: 'CSE',
    year: 'III',
    gender: 'Female',
    phone: '9398786824',
    vertical: 'Marketing',
    position: 'Co-ordinator',
    linkedin: 'https://www.linkedin.com/in/chethana-laxmi-devarasetty',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:12:50',
    email: 'harshavignan07@gmail.com',
    name: 'T MANI HARSHA',
    regNo: '251FA18857',
    branch: 'ACSE',
    year: 'II',
    gender: 'Male',
    phone: '9948794684',
    vertical: 'Finance & Logistics',
    position: 'Co-ordinator',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:26:52',
    email: 'vu.241fa04d82@gmail.com',
    name: 'Mohammed Sahazad Khan',
    regNo: '241FA04D82',
    branch: 'CSE',
    year: 'III',
    gender: 'Male',
    phone: '8260722846',
    vertical: 'Creative & Designing',
    position: 'Co-ordinator',
    linkedin: 'https://www.linkedin.com/in/mohammed-sahazad-khan-439926379',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:35:34',
    email: 'jsai66527@gmail.com',
    name: 'N. Jeevan Sai',
    regNo: '241FK01086',
    branch: 'BBA',
    year: 'III',
    gender: 'Male',
    phone: '9381056955',
    vertical: 'Resource & Counselling',
    position: 'Co-ordinator',
    linkedin: 'https://www.linkedin.com/in/jeevan-sai-94611538b',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:03:22',
    email: 'lakshmisaisunkara3@gmail.com',
    name: 'Lakshmi sai',
    regNo: '241FA18400',
    branch: 'AIML',
    year: 'III',
    gender: 'Female',
    phone: '9182250182',
    vertical: 'Media Relations',
    position: 'Secretary',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:04:52',
    email: 'honeyatwork23@gmail.com',
    name: 'CHADALAVADA RUCHIR VENKATA CHOWDARY',
    regNo: '241FA04011',
    branch: 'CSE',
    year: 'III',
    gender: 'Male',
    phone: '9390778081',
    vertical: 'Creative & Designing',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/ruchir-chadalavada-329b9932a',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:05:08',
    email: 'rapkookmin@gmail.com',
    name: 'Ch.Pragna',
    regNo: '251FK01025',
    branch: 'BBA',
    year: 'II',
    gender: 'Female',
    phone: '7207293375',
    vertical: 'Public Relations',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/pragna-ch-1291a8363',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:05:44',
    email: 'kadavakolluchaityasri@gmail.com',
    name: 'K.Chaitya Sri',
    regNo: '241FA01015',
    branch: 'Biotechnology',
    year: 'III',
    gender: 'Female',
    phone: '7893879099',
    vertical: 'Resource & Counselling',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/kadavakollu-chaityasri-45b83a32b',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:07:01',
    email: 'hemahamsika2207@gmail.com',
    name: 'T.Hamsika',
    regNo: '241fa20016',
    branch: 'CSBS',
    year: 'III',
    gender: 'Female',
    phone: '6300525600',
    vertical: 'Public Relations',
    position: 'Secretary',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:18:20',
    email: 'rupasriparuchuri@gmail.com',
    name: 'Rupa Sri paruchuri',
    regNo: '241FA04B10',
    branch: 'CSE',
    year: 'III',
    gender: 'Female',
    phone: '9440794629',
    vertical: 'Creative & Designing',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/rupa-sri-paruchuri-b4775232a',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:19:34',
    email: 'chmaheshchmahesh2432@gmail.com',
    name: 'Ch. Mahesh',
    regNo: '241FA05225',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '6300560787',
    vertical: 'Corporate Communication',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/mahesh-chipuri-5b921338a',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:19:36',
    email: 'chandra2642006@gmail.com',
    name: 'B.chandra shekar sai ram',
    regNo: '241FA05224',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '9441863617',
    vertical: 'Resource & Counselling',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/chandra-shekar-sai-ram-boppana-42166732a',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:26:34',
    email: 'saraswathitholeti@gmail.com',
    name: 'Saraswathi',
    regNo: '251FA18869',
    branch: 'AIML',
    year: 'II',
    gender: 'Female',
    phone: '7702533916',
    vertical: 'Marketing',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/bala-surya-saraswathi-tholeti-3382a927b',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:42:52',
    email: 'santoshreddyharisantosh@gmail.com',
    name: 'S. Hari Santosh Reddy',
    regNo: '241FA05214',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '6303356662',
    vertical: 'Finance & Logistics',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/hari-santosh-reddy-sunkara-33797b30a',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:57:17',
    email: 'avinashmuvva444@gmail.com',
    name: 'M.Avinash',
    regNo: '241FA23042',
    branch: 'Data Science',
    year: 'III',
    gender: 'Male',
    phone: '7396710313',
    vertical: 'Finance & Logistics',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/muvva-avinash-80575232a',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:03:36',
    email: 'vyshnavi.p2206@gmail.com',
    name: 'P.Lalitha Vyshnavi',
    regNo: '241FA18341',
    branch: 'AIML',
    year: 'III',
    gender: 'Female',
    phone: '8185981531',
    vertical: 'Marketing',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/lalithavyshnavi-p',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 14:18:19',
    email: 'pradyumna@machavaram.com',
    name: 'M.Pradyumna',
    regNo: '241FA05202',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '9557982519',
    vertical: 'Corporate Communication',
    position: 'Secretary',
    linkedin: 'www.linkedin.com/in/pradyumna-machavaram-26276932a',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:03:28',
    email: 'sanipinidimohanapravalika2501@gmail.com',
    name: 'S.Mohana pravalika',
    regNo: '251FA14062',
    branch: 'Bioinformatics',
    year: 'II',
    gender: 'Female',
    phone: '9440981665',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:03:37',
    email: 'aadarsitam08@gmail.com',
    name: 'M. Aadarsita',
    regNo: '251FV01008',
    branch: 'BBA.LLB',
    year: 'II',
    gender: 'Female',
    phone: '9391201164',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:03:42',
    email: 'manishagude39@gmail.com',
    name: 'Manisha Gude',
    regNo: '241FA04A91',
    branch: 'CSE',
    year: 'III',
    gender: 'Female',
    phone: '9553760382',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:25:58',
    email: 'nelakurthisandeep25@gmail.com',
    name: 'Sandeep Nelakurthi',
    regNo: '261FA04681',
    branch: 'CSE core',
    year: 'I',
    gender: 'Male',
    phone: '7972093425',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'Sandeep Nelakurthi',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:04:06',
    email: 'Gowthamvignan4569@gmail.com',
    name: 'D. Gowtham',
    regNo: '261FA04569',
    branch: 'CSE',
    year: 'I',
    gender: 'Male',
    phone: '8247694236',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:04:14',
    email: 'ruthwikchejarla@gmail.com',
    name: 'Ch.Ruthwik',
    regNo: '261FA04B87',
    branch: 'CSE(AI/DS)',
    year: 'I',
    gender: 'Male',
    phone: '9347132755',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:04:18',
    email: 'j.m.d.anil25@gmail.com',
    name: 'Jallepalli Mouli Durga Anil',
    regNo: '261FA19010',
    branch: 'ACSE',
    year: 'I',
    gender: 'Male',
    phone: '7382912327',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:04:22',
    email: 'medidhagiricharan@gmail.com',
    name: 'Giri Charan',
    regNo: '262FA19011',
    branch: 'ACSE',
    year: 'I',
    gender: 'Male',
    phone: '8639580637',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:04:37',
    email: 'karthikeya.v2009@gmail.com',
    name: 'Karthikeya Voleti',
    regNo: '261FA19008',
    branch: 'ACSE (Cybersecurity)',
    year: 'I',
    gender: 'Male',
    phone: '9390613670',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:05:08',
    email: 'hanisha.deevi04@gmail.com',
    name: 'Deevi.Hanisha',
    regNo: '261FA19003',
    branch: 'CSE CS',
    year: 'I',
    gender: 'Female',
    phone: '6304195234',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:05:20',
    email: 'pothakamurilalithajayasree@gmail.com',
    name: 'Lalitha Jayasree',
    regNo: '251FA18682',
    branch: 'AIML',
    year: 'II',
    gender: 'Female',
    phone: '8639023254',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/lalitha-jaya-sree-pothakamuri-111914385',
    residence: 'Day Scholar'
  },

  // Page 2 / 8 / 14
  {
    timestamp: '9-18-2026 12:05:27',
    email: 'pavantavva4444@gmail.com',
    name: 'T. Pavan',
    regNo: '241FA05238',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '8121623409',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:05:32',
    email: 'thanveersk303@gmail.com',
    name: 'Thanveer shaik',
    regNo: '261FA04886',
    branch: 'CSE',
    year: 'I',
    gender: 'Male',
    phone: '7013134669',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:05:34',
    email: 'sruthibhavya06@gmail.com',
    name: 'Katta Bhavya Sruthi',
    regNo: '261FA04670',
    branch: 'CSE core',
    year: 'I',
    gender: 'Female',
    phone: '9491697090',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:05:43',
    email: 'killadamonica@gmail.com',
    name: 'K.V.S.Monica',
    regNo: '251FA18387',
    branch: 'AIML',
    year: 'II',
    gender: 'Female',
    phone: '8019298683',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/monica-killada-a48330389',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:05:47',
    email: 'sudhakallehari29@gmail.com',
    name: 'K. Sudha',
    regNo: '251FA14032',
    branch: 'Bioinformatics',
    year: 'II',
    gender: 'Female',
    phone: '9347574584',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'Sudha Kalle',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:05:52',
    email: 'chaitanyakapa1003@gmail.com',
    name: 'Kapa venkata naga chaitanya krishna',
    regNo: '251FA18353',
    branch: 'CSE-AIML',
    year: 'II',
    gender: 'Male',
    phone: '6302287449',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:05:54',
    email: 'sabbineninavasai11@gmail.com',
    name: 'Sabbineni Navasai',
    regNo: '251FA18731',
    branch: 'AI AND ML',
    year: 'II',
    gender: 'Female',
    phone: '9121682411',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/sabbineni-navasai11',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:06:30',
    email: 'lakshminarayanaala13@gmail.com',
    name: 'A.Lakshmi Narayana',
    regNo: '241FA05171',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '6301274689',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:07:01',
    email: 'dhanushkurra@gmail.com',
    name: 'Dhanush K',
    regNo: '261FA14049',
    branch: 'Bio-informatics',
    year: 'I',
    gender: 'Male',
    phone: '9030325500',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:07:35',
    email: 'rajmrudula0@gmail.com',
    name: 'Godesi Raja Mrudula',
    regNo: '261FA14091',
    branch: 'Bioinformatics',
    year: 'I',
    gender: 'Female',
    phone: '8309489139',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:07:48',
    email: 'maahin.230808@gmail.com',
    name: 'Mohammad Maahin Ahamed',
    regNo: '251FA25034',
    branch: 'ECE - VLSI',
    year: 'II',
    gender: 'Male',
    phone: '8885055134',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:08:08',
    email: 'md.rashi.1979@gmail.com',
    name: 'Rashiya Rezwan',
    regNo: '251FA18709',
    branch: 'ACSE',
    year: 'II',
    gender: 'Female',
    phone: '8500914725',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/rashiya-rezwan-9b4a58383',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:08:18',
    email: 'manognesh2428@gmail.com',
    name: 'Manognesh',
    regNo: '261LA25006',
    branch: 'ECE',
    year: 'II',
    gender: 'Male',
    phone: '8688197982',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:08:20',
    email: 'ndivyabhavana@gmail.com',
    name: 'Neeli Divya Bhavana',
    regNo: '261FA04C90',
    branch: 'CSE',
    year: 'I',
    gender: 'Female',
    phone: '9346105352',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:08:29',
    email: 'krishnarakesh.kolla@gmail.com',
    name: 'Krishna Rakesh Kolla',
    regNo: '231FA14132',
    branch: 'Bioinformatics',
    year: 'IV',
    gender: 'Male',
    phone: '6305845059',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:08:34',
    email: 'kollapudikomalisri@gmail.com',
    name: 'Komali Sri Harshitha',
    regNo: '261FA19174',
    branch: 'CSECS',
    year: 'I',
    gender: 'Female',
    phone: '8688750661',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/komalisri-kollapudi-3ba0b4433',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:08:44',
    email: 'priyakandukuri020@gmail.com',
    name: 'Priya kandukuri',
    regNo: '251fa16005',
    branch: 'BME',
    year: 'II',
    gender: 'Female',
    phone: '8019106466',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/priya-kandukuri-508199290',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:08:49',
    email: 'roronoazororo28@gmail.com',
    name: 'Badarinadh V',
    regNo: '241FA01042',
    branch: 'Biotechnology',
    year: 'III',
    gender: 'Male',
    phone: '8500753400',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:08:51',
    email: 'aryanprathnasvellaturi@gmail.com',
    name: 'Aryan Prathnas Vellaturi',
    regNo: '261FA04006',
    branch: 'CSE',
    year: 'I',
    gender: 'Male',
    phone: '7842872211',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:09:01',
    email: 'bharadwaj.27@outlook.com',
    name: 'Bharadwaj Thimmisetti',
    regNo: '251FA05272',
    branch: 'ECE',
    year: 'II',
    gender: 'Male',
    phone: '7386630388',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/bharadwaj-thimmisetti-b35622383',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:09:19',
    email: 'shahistashaik502@gmail.com',
    name: 'SM Shahista Fathima',
    regNo: '251FA01071',
    branch: 'Biotechnology',
    year: 'II',
    gender: 'Female',
    phone: '7207714958',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/shaik-shahista-3b9863269',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:09:22',
    email: 'dinesh798130@gmail.com',
    name: 'P DINESH KUMAR',
    regNo: '251FA18677',
    branch: 'AIML',
    year: 'II',
    gender: 'Male',
    phone: '9391395501',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:09:48',
    email: 'manendragunti@gmail.com',
    name: 'G.Manendra',
    regNo: '241FA05086',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '9014702415',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/manendra-gunti-823b9032a',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:09:55',
    email: 'mr.nadendlasaisalman@gmail.com',
    name: 'Nadendla Sai Salman',
    regNo: '251FA05177',
    branch: 'ECE',
    year: 'II',
    gender: 'Male',
    phone: '7569632988',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/nadendla-sai-salman-013878411',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:10:26',
    email: 'keerthanjames42@gmail.com',
    name: 'Keerthan James',
    regNo: '241fa01017',
    branch: 'Biotechnology',
    year: 'III',
    gender: 'Male',
    phone: '9676284666',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:11:08',
    email: 'mohanaravuru2008@gmail.com',
    name: 'Rns mohana priya',
    regNo: '261FA01019',
    branch: 'Biotechnology',
    year: 'I',
    gender: 'Female',
    phone: '6302526359',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:11:47',
    email: 'yamininagamani77@gmail.com',
    name: 'Nagamani yamini',
    regNo: '261FA15059',
    branch: 'Food technology',
    year: 'I',
    gender: 'Female',
    phone: '9885548163',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'Yamininagamani',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:12:07',
    email: 'munnalurinymisa@gmail.com',
    name: 'Nymisa Munnaluri',
    regNo: '261FA19018',
    branch: 'CSECS',
    year: 'I',
    gender: 'Female',
    phone: '9491553268',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:12:12',
    email: 'sujaithimulksuryachandra@gmail.com',
    name: 'Sm surya chandra',
    regNo: '261FA18157',
    branch: 'CSE AIML',
    year: 'I',
    gender: 'Male',
    phone: '6305547635',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: 'Sm Surya Chandra',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:12:24',
    email: 'vyrajavallineelam@gmail.com',
    name: 'Neelam venkata yeathi rajavalli',
    regNo: '251FA18595',
    branch: 'ACSE',
    year: 'II',
    gender: 'Female',
    phone: '9346414735',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'www.linkedin.com/in/vyrajavallineelam',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:12:35',
    email: 'kondrakuntaamrutha@gmail.com',
    name: 'Kondrakunta Amrutha',
    regNo: '251FA05127',
    branch: 'ECE',
    year: 'II',
    gender: 'Female',
    phone: '7396694499',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/kondrakunta-amrutha-7ba62a37b',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:13:45',
    email: 'harikrishnagutta4@gmail.com',
    name: 'GUTTA HARI KRISHNA CHOWDARY',
    regNo: '261FA02066',
    branch: 'Chemical',
    year: 'I',
    gender: 'Male',
    phone: '9618624687',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },

  // Page 3 / 9 / 15
  {
    timestamp: '9-18-2026 12:13:54',
    email: 'vaishnavivaddiganti@gmail.com',
    name: 'Vaddiganti Naga vaishnavi',
    regNo: '261FA04740',
    branch: 'B.Tech - CSE',
    year: 'I',
    gender: 'Female',
    phone: '6305110212',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/vaishnavi-vaishnavi-983272438',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:13:59',
    email: 'saniyaiffat.k@gmail.com',
    name: 'K.Saniya iffat',
    regNo: '251FA14034',
    branch: 'BTech Bioinformatics',
    year: 'II',
    gender: 'Female',
    phone: '9281400705',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/kandi-saniya-iffat-89aa50374',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:14:17',
    email: 'chinnikeerthana2@gmail.com',
    name: 'Kotra Keerthana',
    regNo: '251FA18431',
    branch: 'AIML',
    year: 'II',
    gender: 'Female',
    phone: '9392814349',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/keerthana-kotra-678567428',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:14:21',
    email: 'manchikantinandini107@gmail.com',
    name: 'Manchikanti siva Nandini',
    regNo: '261FA18487',
    branch: 'AIML',
    year: 'I',
    gender: 'Female',
    phone: '8309349551',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'Manchikanti siva Nandini',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:14:35',
    email: 'pragnateja.engg@gmail.com',
    name: 'I.pragna teja',
    regNo: '251FA18300',
    branch: 'AI&ML',
    year: 'II',
    gender: 'Female',
    phone: '9391179879',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/pragna-teja-088442384',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:14:35',
    email: 'pathiyalalakshmitulasi@gmail.com',
    name: 'P.lakshmi tulasi',
    regNo: '251FA18651',
    branch: 'AI AND ML',
    year: 'II',
    gender: 'Female',
    phone: '8328058175',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'www.linkedin.com/in/lakshmi-tulasi-pathiyalau',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:15:06',
    email: 'saiindira16@gmail.com',
    name: 'T. Sai Indira',
    regNo: '241FA05143',
    branch: 'ECE',
    year: 'III',
    gender: 'Female',
    phone: '9059051637',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/sai-indira-thumu-4015b932a',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:15:17',
    email: 'vutukurikarthik796@gmail.com',
    name: 'Vutukuri Yuva Venkata Karthik',
    regNo: '241FA18158',
    branch: 'AIML',
    year: 'III',
    gender: 'Male',
    phone: '9908928114',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/vutukuri-karthik-733b9432a',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:15:27',
    email: 'kallamushitha1@gmail.com',
    name: 'Kallam Ushitha',
    regNo: '251FA18328',
    branch: 'CSE-AIML',
    year: 'II',
    gender: 'Female',
    phone: '8179364314',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/ushitha-reddy-k-352443355',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:15:28',
    email: 'singamjyoshnavi@gmail.com',
    name: 'S jyoshnavi',
    regNo: '251FA14068',
    branch: 'Bioinformatics',
    year: 'II',
    gender: 'Female',
    phone: '8125256922',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:16:49',
    email: 'yasaswiniyandrapalli@gmail.com',
    name: 'Y.Yasaswini',
    regNo: '261FA04511',
    branch: 'CSE',
    year: 'I',
    gender: 'Female',
    phone: '9966791666',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:17:08',
    email: 'kumbhasridurga@gmail.com',
    name: 'K sri durga',
    regNo: '251FA05135',
    branch: 'ECE',
    year: 'II',
    gender: 'Female',
    phone: '7075420502',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:17:34',
    email: 'renusripasupuleti@gmail.com',
    name: 'Renusri verra venkata satya vagdevi.pasupuleti',
    regNo: '251FA18722',
    branch: 'CSE(AI&ML)',
    year: 'II',
    gender: 'Female',
    phone: '7013056653',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/renusri-p',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:18:02',
    email: 'kolanuvadabhavitha@gmail.com',
    name: 'K.bhavitha devi',
    regNo: '261FA04392',
    branch: 'CSE',
    year: 'I',
    gender: 'Female',
    phone: '9640483678',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:18:28',
    email: 'samyuktharayapati@gmail.com',
    name: 'R.G.SAMYUKTHA',
    regNo: '251FA25049',
    branch: 'ECE-VLSI',
    year: 'II',
    gender: 'Female',
    phone: '7075081415',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:18:29',
    email: 'shaiksaniya12396@gmail.com',
    name: 'Sk.Saniya',
    regNo: '251FA05257',
    branch: 'ECE',
    year: 'II',
    gender: 'Female',
    phone: '7989616329',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:19:07',
    email: 'mutyalat2288@gmail.com',
    name: 'mutyala teja',
    regNo: '251fa05175',
    branch: 'ECE',
    year: 'II',
    gender: 'Male',
    phone: '9346709366',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:19:38',
    email: 'chaluvadisaiashritha22@gmail.com',
    name: 'Chaluvadi Sai Ashritha',
    regNo: '261FA14019',
    branch: 'Bioinformatics',
    year: 'I',
    gender: 'Female',
    phone: '8522843213',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'Chaluvadi Sai Ashritha',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:19:40',
    email: 'vardhanarjun33@gmail.com',
    name: 'KOLIPARTHI VARDHAN ARJUN',
    regNo: '241FA05210',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '9949776414',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/vardhan-arjun-310573218',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:19:58',
    email: 'Shabana2652008@gmail.com',
    name: 'Sk.Ahammad Shabana arshiya',
    regNo: '261FA01079',
    branch: 'Biotechnology',
    year: 'I',
    gender: 'Female',
    phone: '9381815156',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:20:10',
    email: 'vishnukarthik6464@gmail.com',
    name: 'K. Sri Vishnu Karthik',
    regNo: '241FA05241',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '9392646463',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/kuchipudisrivishnukarthik',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:20:27',
    email: 'surapanenisathwika@gmail.com',
    name: 'Sathwika',
    regNo: '251FA04B80',
    branch: 'CSE',
    year: 'II',
    gender: 'Female',
    phone: '7032300591',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:22:25',
    email: 'dollyharshinikommineni@gmail.com',
    name: 'Dolly Harshini Kommineni',
    regNo: '251FA04577',
    branch: 'CSE',
    year: 'II',
    gender: 'Female',
    phone: '9014605085',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/dollyharshini-kommineni-4160bb438',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:22:39',
    email: 'mksreecharanrr@gmail.com',
    name: 'M.K.Sree charan',
    regNo: '241FA05217',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '6301984851',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/mk-sree-charan-448537389',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:23:02',
    email: 'pandasreespurthi@gmail.com',
    name: 'P Sree Spurthi',
    regNo: '241FK01094',
    branch: 'BBA',
    year: 'III',
    gender: 'Female',
    phone: '9441936641',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/panda-sree-spurthi-7b4434371',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:23:30',
    email: 'maoreez@gmail.com',
    name: 'Oriel Jnr Ncube',
    regNo: '251FA08047',
    branch: 'Mechanical',
    year: 'II',
    gender: 'Male',
    phone: '06303717489',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:23:44',
    email: 'pvssraju7@gmail.com',
    name: 'P.v.s.s Raju',
    regNo: '261FA04598',
    branch: 'CSE(CORE)',
    year: 'I',
    gender: 'Male',
    phone: '7981793627',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/venkata-siva-sai-raju-pulidindi-930507428',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:24:04',
    email: 'sarvani.580@gmail.com',
    name: 'Sarvani',
    regNo: '251FA14070',
    branch: 'Bioinformatics',
    year: 'II',
    gender: 'Female',
    phone: '8247465957',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/sarvani-t-ba01b4377',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:25:23',
    email: 'rishiksrinivasreddy@gmail.com',
    name: 'BANNURU RISHIK SRINIVASA REDDY',
    regNo: '2611FA04563',
    branch: 'B.tech(cse)',
    year: 'I',
    gender: 'Male',
    phone: '07671908897',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/rishik-srinivas-reddy-039522360',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:25:53',
    email: 'vu.241fa04a48@gmail.com',
    name: 'Divyanshu Raj',
    regNo: '241FA04A48',
    branch: 'CSE',
    year: 'III',
    gender: 'Male',
    phone: '8809264126',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/divyanshuraj084',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:26:03',
    email: 'vustudy25029@gmail.com',
    name: 'K Bhargava Sai Venkata Ganesh',
    regNo: '251FA25029',
    branch: 'ECE VLSI',
    year: 'II',
    gender: 'Male',
    phone: '9618523362',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:26:26',
    email: 'roshinigandham11@gmail.com',
    name: 'Gandham Roshini',
    regNo: '261FA01030',
    branch: 'Biotechnology',
    year: 'I',
    gender: 'Female',
    phone: '9550881776',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/roshini-gandham-46a99741a',
    residence: 'Day Scholar'
  },

  // Page 4 / 10 / 16
  {
    timestamp: '9-18-2026 12:28:51',
    email: 'monikadevianumukonda@gmail.com',
    name: 'MONIKA DEVI ANUMUKONDA',
    regNo: '261LA25008',
    branch: 'ECE-VLSI',
    year: 'II',
    gender: 'Female',
    phone: '9494817276',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:28:54',
    email: 'lakshmisahasra@gmail.com',
    name: 'Lakshmi Sahasra',
    regNo: '251FA04C60',
    branch: 'CSE',
    year: 'II',
    gender: 'Female',
    phone: '8333889773',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/sahasra-tunuguntla-926249308',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:29:53',
    email: 'siddarth2656@gmail.com',
    name: 'K siddarth',
    regNo: '251FA05129',
    branch: 'ECE',
    year: 'II',
    gender: 'Male',
    phone: '9392535758',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/siddarth-koritala-39693436b',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:31:05',
    email: 'khyathireddysadi@gmail.com',
    name: 'Sadi.Khyathi',
    regNo: '261FA18844',
    branch: 'CSE AIML',
    year: 'I',
    gender: 'Female',
    phone: '9652089471',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:31:05',
    email: 'sravaniganta87500@gmail.com',
    name: 'Ganta sravani',
    regNo: '261FA18669',
    branch: 'CSE - AIML',
    year: 'I',
    gender: 'Female',
    phone: '8639070148',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:34:58',
    email: 'nageshkaranam09@gmail.com',
    name: 'K.Nagesh',
    regNo: '241FA05057',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '6303131893',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/nagesh-karanam-ababb6319',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:35:12',
    email: 'devikakomatineni@gmail.com',
    name: 'K Devika',
    regNo: '261FA18639',
    branch: 'AI and ML',
    year: 'I',
    gender: 'Female',
    phone: '6304799745',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/devika-komatineni-3157b1426',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:36:12',
    email: 'vpavani2007@gmail.com',
    name: 'Vuyyuru Pavani',
    regNo: '241FA05170',
    branch: 'ECE',
    year: 'III',
    gender: 'Female',
    phone: '9346583315',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'Pavani Vuyyuru',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:36:38',
    email: 'rasagnavollala25@gmail.com',
    name: 'V. Rasagna',
    regNo: '251FA16041',
    branch: 'Biomedical engineering',
    year: 'II',
    gender: 'Female',
    phone: '9182401166',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'Rasagna vollala',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:40:13',
    email: 'greeshmaganta40@gmail.com',
    name: 'Greeshma',
    regNo: '251FK01042',
    branch: 'BBA',
    year: 'II',
    gender: 'Female',
    phone: '6305414887',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:40:21',
    email: 'mohant200807@gmail.com',
    name: 'T.Mohan Kumar',
    regNo: '261FA23078',
    branch: 'Data science',
    year: 'I',
    gender: 'Male',
    phone: '8106224688',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:40:28',
    email: 'petetirani7@gmail.com',
    name: 'P Rani',
    regNo: '251FA04951',
    branch: 'CSE',
    year: 'II',
    gender: 'Female',
    phone: '7997644150',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/rani-peteti-b539b03b1',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:41:59',
    email: 'gowthamchowdary200@gmail.com',
    name: 'Gowtham',
    regNo: '261FA21003',
    branch: 'RA',
    year: 'I',
    gender: 'Male',
    phone: '9493240210',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:43:20',
    email: 'sivanipagadala07@gmail.com',
    name: 'P Naga Sivani',
    regNo: '251FA05194',
    branch: 'ECE',
    year: 'II',
    gender: 'Female',
    phone: '9441182313',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:44:57',
    email: 'deekshitaadivanne@gmail.com',
    name: 'Deekshita Adivanne',
    regNo: '251FA25013',
    branch: 'ECE VLSI',
    year: 'II',
    gender: 'Female',
    phone: '7815930408',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'Deekshita Adivanne',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:45:59',
    email: 'harshitha.v@gmail.com',
    name: 'V. Harshitha',
    regNo: '251FA04C89',
    branch: 'CSE',
    year: 'II',
    gender: 'Female',
    phone: '9014630747',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/harshitha-vakkalagadda-b038593ab',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:46:01',
    email: 'tejaswinidasari19@gmail.com',
    name: 'D.Tejaswini',
    regNo: '251FA04262',
    branch: 'CSE',
    year: 'II',
    gender: 'Female',
    phone: '9666000434',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/tejaswini-dasari-83b5b6394',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:49:14',
    email: 'vulapushivakeshav@gmail.com',
    name: 'Shiva keshav vulapu',
    regNo: '261FA04750',
    branch: 'CSE- core',
    year: 'I',
    gender: 'Male',
    phone: '9390276864',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/shiva-keshav-vulapu',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:48:04',
    email: 'udaysakshath847@gmail.com',
    name: 'M.udaya sakshath',
    regNo: '251FA25035',
    branch: 'ECE VLSI',
    year: 'II',
    gender: 'Male',
    phone: '9346962569',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:49:30',
    email: 'tejasreemajeti2410@gmail.com',
    name: 'M.Tejasri',
    regNo: '241FA05167',
    branch: 'ECE',
    year: 'III',
    gender: 'Female',
    phone: '9392792287',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:51:10',
    email: 'prodduturigopichandu@gmail.com',
    name: 'P Gopichandu',
    regNo: '251FA18691',
    branch: 'AIML',
    year: 'II',
    gender: 'Male',
    phone: '9154711891',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/prodduturi-gopi-chandu-310333389',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:51:48',
    email: 'vu.241fa04a54@gmail.com',
    name: 'Maseera Sk',
    regNo: '241FA04A54',
    branch: 'CSE',
    year: 'III',
    gender: 'Female',
    phone: '9346616217',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:53:08',
    email: 'husnavu02@gmail.com',
    name: 'Sk.Husna Begum',
    regNo: '251fa04h58',
    branch: 'CSE',
    year: 'II',
    gender: 'Female',
    phone: '9247057999',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/husna-begum-sk-398861398',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:53:18',
    email: 'gantasalasriharshitha@gmail.com',
    name: 'G.Harshitha',
    regNo: '251FA14022',
    branch: 'Btech-Bioinformatics',
    year: 'II',
    gender: 'Female',
    phone: '9491702215',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/sri-harshitha-ghantasala-b8375438a',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:54:47',
    email: 'vinishat82@gmail.com',
    name: 'Thumma Mariya Vinisha',
    regNo: '261FK01211',
    branch: 'BBA',
    year: 'I',
    gender: 'Female',
    phone: '9014636586',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:59:14',
    email: 'kalavalachandu02@gmail.com',
    name: 'KALAVALA CHANDU SANJAY RAMA SWAMI',
    regNo: '261FK01087',
    branch: 'BBA',
    year: 'II',
    gender: 'Male',
    phone: '9346032334',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:00:08',
    email: 'vijayalakshmi572008@gmail.com',
    name: 'Maddiboina Vijaya Lakshmi',
    regNo: '251FA18467',
    branch: 'CSE- AIML',
    year: 'II',
    gender: 'Female',
    phone: '9154834095',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/vijaya-lakshmi-maddiboina-b8107642b',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:00:16',
    email: 'gnaneswarkaramsetty@gmail.com',
    name: 'K Gnaneswar',
    regNo: '251FA05128',
    branch: 'AI ML',
    year: 'II',
    gender: 'Male',
    phone: '9295659080',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:03:46',
    email: 'sarathpayyavula@gmail.com',
    name: 'p.sarath sai',
    regNo: '251FA05316',
    branch: 'ECE',
    year: 'II',
    gender: 'Male',
    phone: '9059398262',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/payyavula-sarath-sai-860995334',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:05:40',
    email: 'saibharataravapalli@gmail.com',
    name: 'ARAVAPALLI SAI BHARAT CHOWDARY',
    regNo: '251FA05009',
    branch: 'ECE',
    year: 'II',
    gender: 'Male',
    phone: '9573732933',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/sai-bharat-chowdary-aravapalli-837211372',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:05:59',
    email: 'sankuriparimala@gmail.com',
    name: 'S.Parimala',
    regNo: '251FA14063',
    branch: 'BIOINFORMATICS',
    year: 'II',
    gender: 'Female',
    phone: '8309758327',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/parimala-sankuri-521366427',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:06:28',
    email: 'likithareddy1103@gmail.com',
    name: 'T.Likitha Reddy',
    regNo: '251FA04C06',
    branch: 'CSE',
    year: 'II',
    gender: 'Female',
    phone: '9390226987',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'www.linkedin.com/in/likitha-tamma-28647b390',
    residence: 'Day Scholar'
  },

  // Page 5 / 11 / 17
  {
    timestamp: '9-18-2026 13:08:18',
    email: 'sonytatinati0@gmail.com',
    name: 'Tatinati Sony',
    regNo: '241FA05117',
    branch: 'ECE',
    year: 'III',
    gender: 'Female',
    phone: '7671000206',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:10:14',
    email: 'pardhvini2009@gmail.com',
    name: 'Pardhvini',
    regNo: '261FA04683',
    branch: 'CSE',
    year: 'I',
    gender: 'Female',
    phone: '9392133668',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/pardhvini-undefined-753a49320',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:13:27',
    email: 'sravyaseshagirirao@gmail.com',
    name: 'Ch Sravya',
    regNo: '241FA05139',
    branch: 'ECE',
    year: 'III',
    gender: 'Female',
    phone: '8520851571',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/sravya-chatra-1b7b9732a',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:14:38',
    email: 'srisravanya070208@gmail.com',
    name: 'BOINA SRI SRAVANYA',
    regNo: '261FA04181',
    branch: 'CSE - Core',
    year: 'I',
    gender: 'Female',
    phone: '7995779426',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:15:10',
    email: 'chaitnyasrisaisuddapalli123@gmail.com',
    name: 'Chaitnya sri sai Suddapalli',
    regNo: '251FA04B69',
    branch: 'CSE',
    year: 'II',
    gender: 'Male',
    phone: '9966791965',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/chaitu-suddapalli-b2177b3b2',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:22:06',
    email: 'srujanamadala316@gmail.com',
    name: 'Madala srujana',
    regNo: '261FA04491',
    branch: 'CSE',
    year: 'I',
    gender: 'Female',
    phone: '8247515559',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:22:08',
    email: 'sanjukthapassam@gmail.com',
    name: 'P.sanjuktha',
    regNo: '261FA04B86',
    branch: 'CSE',
    year: 'I',
    gender: 'Female',
    phone: '8686966902',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:24:38',
    email: 'workkarthiku@gmail.com',
    name: 'Ch.karthik',
    regNo: '261FA04A91',
    branch: 'CSE',
    year: 'I',
    gender: 'Male',
    phone: '8019974779',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:24:41',
    email: 'shanmukhakorrapati@gmail.com',
    name: 'Korrapati Shanmukha Sai Krishna',
    regNo: '251FA18418',
    branch: 'AI&ML',
    year: 'II',
    gender: 'Male',
    phone: '9346355408',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:27:08',
    email: 'jayasrisankaramanchi@gmail.com',
    name: 'Jayasri',
    regNo: '241FA01055',
    branch: 'Biotechnology',
    year: 'III',
    gender: 'Female',
    phone: '9032807565',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/jayasri-sankaramanchi-65668933b',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:28:40',
    email: 'kalyanijoshna210@gmail.com',
    name: 'Kkalyanijoshna',
    regNo: '251FA25028',
    branch: 'ECEVLSI',
    year: 'II',
    gender: 'Female',
    phone: '9492388877',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:43:58',
    email: 'gopikumar4126@gmail.com',
    name: 'V. Gopi praveen kumar',
    regNo: '241LA08005',
    branch: 'MECHANICAL ENGINEERING',
    year: 'IV',
    gender: 'Male',
    phone: '6302178973',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/gopi-praveen-kumar-vinjumuri-80a17032b',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 13:51:03',
    email: 'nvsaianila@gmail.com',
    name: 'N.V.Sai Anila',
    regNo: '241FA04A87',
    branch: 'CSE',
    year: 'III',
    gender: 'Female',
    phone: '7981575919',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/n-v-sai-anila-989927333',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:53:52',
    email: 'navyalenka009@gmail.com',
    name: 'Lenka . Navya',
    regNo: '251FA15046',
    branch: 'Food Technology',
    year: 'II',
    gender: 'Female',
    phone: '6305105207',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'Lenka navya',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 14:17:32',
    email: 'jakkasaileela02@gmail.com',
    name: 'J.Sai Leela',
    regNo: '251FA18307',
    branch: 'AI ML',
    year: 'II',
    gender: 'Female',
    phone: '6309008913',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/sai-leela-jakka-469160428',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 14:23:14',
    email: 'keerthanakamineni3@gmail.com',
    name: 'Keerthana Kamineni',
    regNo: '251FA18336',
    branch: 'AIML',
    year: 'II',
    gender: 'Female',
    phone: '8688249151',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/keerthana-kamineni-32816b38a',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 14:26:55',
    email: 'abhinavap176@gmail.com',
    name: 'POLEBOINA ABHINAVA TEJ',
    regNo: '261FA04A15',
    branch: 'CSE',
    year: 'I',
    gender: 'Male',
    phone: '9440202176',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/abhi-p-18a1b6438',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 14:27:52',
    email: 'sravanireddimaddireddy@gmail.com',
    name: 'Maddireddy sravani',
    regNo: '261FA04B58',
    branch: 'CSE',
    year: 'I',
    gender: 'Female',
    phone: '7013823887',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'Maddireddy sravani',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 15:18:29',
    email: 'gaurav.kr2u@gmail.com',
    name: 'Gaurav Kumar',
    regNo: '261FA06067',
    branch: 'EEE',
    year: 'I',
    gender: 'Male',
    phone: '8986696648',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/gaurav-kumar-b39b23421',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 15:24:58',
    email: 'shaikvalimastanntr@gmail.com',
    name: 'MASTAN VALI SHAIK',
    regNo: '251FA25053',
    branch: 'VLSI',
    year: 'II',
    gender: 'Male',
    phone: '9010062684',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'SHAIK MASTAN',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 15:51:43',
    email: 'bolaganiyaswin@gmail.com',
    name: 'B. Yaswin',
    regNo: '251FA04144',
    branch: 'CSE',
    year: 'II',
    gender: 'Male',
    phone: '6281766345',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/bolagani-yaswin-a3b52b389',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 15:57:02',
    email: 'trivenimadala952@gmail.com',
    name: 'MADALA TRIVENI CHOWDHARY',
    regNo: '231FA16004',
    branch: 'BIOMEDICAL',
    year: 'IV',
    gender: 'Female',
    phone: '7981294023',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/triveni-chowdary-madala-b94130324',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 16:01:10',
    email: 'jagadishkudumula9000@gmail.com',
    name: 'Purna jagadish.kudumula',
    regNo: '261FA21085',
    branch: 'Robotics and automation',
    year: 'I',
    gender: 'Male',
    phone: '9000110755',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/jagadish-kudumula-b152a4438',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 16:01:46',
    email: 'bethapudivinaykumar308@gmail.com',
    name: 'Vinay kumar Bethapudi',
    regNo: '251FA18078',
    branch: 'Ai&ML',
    year: 'II',
    gender: 'Male',
    phone: '9494468804',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/vinay-kumar-bethapudi-b56470381',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 16:03:23',
    email: 'brahminikantu2208@gmail.com',
    name: 'K Naga Brahmini',
    regNo: '251FA03014',
    branch: 'Civil',
    year: 'II',
    gender: 'Female',
    phone: '9392370793',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/brahmini-kantu-b020a5376',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 16:03:34',
    email: 'jaswanthsaibalaji8@gmail.com',
    name: 'T.jaswanth sai',
    regNo: '251FA05281',
    branch: 'ECE',
    year: 'II',
    gender: 'Male',
    phone: '8555951032',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 16:06:55',
    email: 'bvenkatavarshit@gmail.com',
    name: 'B.V.Varshit',
    regNo: '261FA18193',
    branch: 'AIML',
    year: 'I',
    gender: 'Male',
    phone: '8328524031',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/venkata-varshit-balivada-7842b142b',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 16:32:41',
    email: 'nagendramouryakosuru@gmail.com',
    name: 'Nagendra mourya',
    regNo: '251FA05131',
    branch: 'ECE',
    year: 'II',
    gender: 'Male',
    phone: '7013221996',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 18:05:03',
    email: 'pamikumari997@gmail.com',
    name: 'Pami kumari',
    regNo: '261FA04C95',
    branch: 'Computer science and engineering',
    year: 'I',
    gender: 'Female',
    phone: '9006092334',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 18:21:17',
    email: 'murari.nishanth21@gmail.com',
    name: 'Murari Nishanth',
    regNo: '251FA04802',
    branch: 'CSE',
    year: 'II',
    gender: 'Male',
    phone: '7981710999',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/nishanth-murari-b61483371',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 18:30:25',
    email: 'kborugati@gmail.com',
    name: 'B. Koushik Varma',
    regNo: '251FA18102',
    branch: 'CSE - AIML',
    year: 'II',
    gender: 'Male',
    phone: '9963315630',
    vertical: 'Corporate Communication',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/koushik-varma-borugati13459',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 18:33:42',
    email: 'saimanideepdaroga2008@gmail.com',
    name: 'DAroga Sai Manideep',
    regNo: '261FA08036',
    branch: 'Mechanical',
    year: 'I',
    gender: 'Male',
    phone: '9396659270',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'www.linkedin.com/in/sai-manideep-undefined-4ba861425',
    residence: 'Day Scholar'
  },

  // Page 6 / 12 / 18
  {
    timestamp: '9-18-2026 18:40:38',
    email: 'gaddamnehasree@gmail.com',
    name: 'G.Neha sree',
    regNo: '261FA18119',
    branch: 'AIML',
    year: 'I',
    gender: 'Female',
    phone: '6300630572',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'Gaddam Neha sree',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 18:49:48',
    email: 'roja12597@gmail.com',
    name: 'Tatinati Roja',
    regNo: '251FA05269',
    branch: 'ECE',
    year: 'II',
    gender: 'Female',
    phone: '8897332819',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 18:52:36',
    email: 'revanthdakupati0@gmail.com',
    name: 'Revanth.D',
    regNo: '241FA05124',
    branch: 'ECE',
    year: 'III',
    gender: 'Male',
    phone: '9966685497',
    vertical: 'Creative & Designing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/revanth-dakupati-348414423',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 19:27:41',
    email: 'sushmasrivenigandla@gmail.com',
    name: 'sushma sri',
    regNo: '251FA18935',
    branch: 'AIML',
    year: 'II',
    gender: 'Female',
    phone: '7093542136',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'sushma sri venigandla',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 19:28:43',
    email: 'prabhinav2057@gmail.com',
    name: 'N.PRANATHI',
    regNo: '241FA14070',
    branch: 'BI',
    year: 'III',
    gender: 'Female',
    phone: '8341615851',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: '',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:48:53',
    email: 'nikhileshalapati90@gmail.com',
    name: 'A Nikhilesh',
    regNo: '231FA04F38',
    branch: 'CSE',
    year: 'IV',
    gender: 'Male',
    phone: '7207336271',
    vertical: null, // Team Representative
    position: 'Team Representative',
    linkedin: 'https://www.linkedin.com/in/nikhileshalapati1912',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 11:58:24',
    email: 'vasanta2609@gmail.com',
    name: 'Vasanta Lakshmi',
    regNo: '231FA04244',
    branch: 'CSE',
    year: 'IV',
    gender: 'Female',
    phone: '9949528256',
    vertical: 'Resource & Counselling',
    position: 'Vertical Lead',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:05:16',
    email: 'pranathisankula@gmail.com',
    name: 'S.pranathi',
    regNo: '231FA01035',
    branch: 'Biotechnology',
    year: 'IV',
    gender: 'Female',
    phone: '7989479717',
    vertical: 'Marketing',
    position: 'Vertical Lead',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:06:46',
    email: 'hansisvm1289@gmail.com',
    name: 'Hansi Mallela',
    regNo: '241FA01047',
    branch: 'Biotechnology',
    year: 'III',
    gender: 'Female',
    phone: '7674801281',
    vertical: 'Media Relations',
    position: 'Vertical Lead',
    linkedin: 'https://www.linkedin.com/in/hansi-mallela-94a67032a',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:32:26',
    email: 'gontla.bindu2005@gmail.com',
    name: 'G.Bindu Venkata Sai Amrutha',
    regNo: '231FA04794',
    branch: 'CSE',
    year: 'IV',
    gender: 'Female',
    phone: '8712366444',
    vertical: 'Finance & Logistics',
    position: 'Vertical Lead',
    linkedin: 'https://www.linkedin.com/in/gontlabindu',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 13:12:06',
    email: 'fathima7735@gmail.com',
    name: 'Mohammed Fathima Khan',
    regNo: '231FA14112',
    branch: 'Bioinformatics',
    year: 'IV',
    gender: 'Female',
    phone: '9963838500',
    vertical: 'Creative & Designing',
    position: 'Vertical Lead',
    linkedin: 'https://www.linkedin.com/public-profile/settings/',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 12:08:33',
    email: 'tsrilatha2005@gmail.com',
    name: 'T.Sri Latha',
    regNo: '241FA01030',
    branch: 'Biotechnology',
    year: 'III',
    gender: 'Female',
    phone: '7382618080',
    vertical: null, // VTR
    position: 'VTR',
    linkedin: 'https://www.linkedin.com/in/tummala-sri-latha-818a4032b',
    residence: 'Inside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:11:58',
    email: 'bhupathirakesh26@gmail.com',
    name: 'MBhupathi Rakesh',
    regNo: '241FA01026',
    branch: 'Btech Biotechnology',
    year: 'III',
    gender: 'Male',
    phone: '7993114713',
    vertical: null, // VTR
    position: 'VTR',
    linkedin: 'https://www.linkedin.com/in/bhupathi-rakesh-mamilla-67aa67376',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 12:49:59',
    email: 'saikowshikattuluri@gmail.com',
    name: 'A Sai Kowshik',
    regNo: '261LA25011',
    branch: 'ECE VLSI',
    year: 'II',
    gender: 'Male',
    phone: '8639660896',
    vertical: 'Finance & Logistics',
    position: 'VTR',
    linkedin: '',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 19:40:12',
    email: 'bhargavipriyareddy3@gmail.com',
    name: 'B R Bhargavi Priya',
    regNo: '241FA14003',
    branch: 'Bioinformatics',
    year: 'III',
    gender: 'Female',
    phone: '9494581244',
    vertical: 'Media Relations',
    position: 'Secretary',
    linkedin: 'https://www.linkedin.com/in/bobbala-rammanagari-bhargavi-priya-02285b32a',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 19:48:09',
    email: 'pranavireddy2006@gmail.com',
    name: 'Somula Pranavi',
    regNo: '231FA14109',
    branch: 'Bioinformatics',
    year: 'IV',
    gender: 'Female',
    phone: '7670938610',
    vertical: 'Corporate Communication',
    position: 'Co-ordinator',
    linkedin: 'https://www.linkedin.com/in/somula-pranavi',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 19:55:19',
    email: 'manidanaboina716@gmail.com',
    name: 'DANABOINA HEMA DURGA MANIKANTA',
    regNo: '231FA16016',
    branch: 'Biomedical Engineering',
    year: 'IV',
    gender: 'Male',
    phone: '6304417066',
    vertical: 'Corporate Communication',
    position: 'Vertical Lead',
    linkedin: 'https://www.linkedin.com/in/danaboina-hema-durga-manikanta-324b9a2b2',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-18-2026 19:55:34',
    email: 'saif.ahamed.sk205@gmail.com',
    name: 'Sk. Saif Ahamed',
    regNo: '241FA01054',
    branch: 'Biotechnology',
    year: 'III',
    gender: 'Male',
    phone: '7382741560',
    vertical: 'Finance & Logistics',
    position: 'Team Member',
    linkedin: '',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 19:59:42',
    email: 'navadeep1817@gmail.com',
    name: 'Navadeep Tammineni',
    regNo: '231fa04895',
    branch: 'CSE',
    year: 'IV',
    gender: 'Male',
    phone: '8688782485',
    vertical: 'Public Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/navadeep-tammineni',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 21:18:15',
    email: 'vu.241fa04328@gmail.com',
    name: 'B.sai praveen',
    regNo: '241FA04328',
    branch: 'CSE',
    year: 'III',
    gender: 'Male',
    phone: '8639577782',
    vertical: 'Resource & Counselling',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/me?trk=p_mwlite_profile_self-secondary_nav',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-18-2026 0:02:33',
    email: '231fa04956@gmail.com',
    name: 'DONTHALA SRI HARI KRISHNA',
    regNo: '231FA04956',
    branch: 'CSE',
    year: 'IV',
    gender: 'Male',
    phone: '7671873341',
    vertical: 'Public Relations',
    position: 'Vertical Lead',
    linkedin: 'https://www.linkedin.com/in/sri-hari-krishna-donthala/',
    residence: 'Outside Hosteller'
  },
  {
    timestamp: '9-19-2026 5:13:00',
    email: 'pavansaidasari06@gmail.com',
    name: 'Venkata Pavan Sai Dasari',
    regNo: '261FA18771',
    branch: 'CSE-AIML',
    year: 'I',
    gender: 'Male',
    phone: '9398307320',
    vertical: 'Marketing',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/pavan-sai-dasari-4a6643431',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-19-2026 8:40:01',
    email: 'lolabhattu1311@gmail.com',
    name: 'Lolabhattu Nikhil Sai Krishna Varma',
    regNo: '241FA19055',
    branch: 'CSE -CS',
    year: 'III',
    gender: 'Male',
    phone: '9390000913',
    vertical: 'Corporate Communication',
    position: 'Co-ordinator',
    linkedin: 'https://www.linkedin.com/in/l-n-s-krishna-varma-b19828307',
    residence: 'Day Scholar'
  },
  {
    timestamp: '9-20-2026 8:51:17',
    email: 'gadepavankumar40@gmail.com',
    name: 'Pavan Kumar',
    regNo: '231FA18074',
    branch: 'AIML',
    year: 'IV',
    gender: 'Male',
    phone: '8522927443',
    vertical: 'Media Relations',
    position: 'Team Member',
    linkedin: 'https://www.linkedin.com/in/pavankumargade09',
    residence: 'Day Scholar'
  }
];

export async function importPdfMembers() {
  try {
    await mongoose.connect(ENV.MONGO_URI);
    console.log(' Connected to MongoDB:', ENV.MONGO_URI);

    // 1. Clear database
    console.log(' Clearing all existing users, attendance, and logs...');
    await Promise.all([
      User.deleteMany({}),
      Attendance.deleteMany({}),
      Event.deleteMany({}),
      EmailLog.deleteMany({}),
      AuditLog.deleteMany({})
    ]);

    // 2. Ensure Verticals exist
    const verticalMap = {};
    for (const vData of DEFAULT_VERTICALS) {
      let vDoc = await Vertical.findOne({ slug: vData.slug });
      if (!vDoc) {
        vDoc = await Vertical.create({
          name: vData.name,
          slug: vData.slug,
          description: vData.description,
          isActive: true
        });
      }
      verticalMap[vData.slug] = vDoc;
      verticalMap[vData.name.toLowerCase()] = vDoc;
    }
    // Also add friendly name mappings
    verticalMap['resource & counselling'] = verticalMap['resource-counselling'];
    verticalMap['r&c'] = verticalMap['resource-counselling'];
    verticalMap['marketing'] = verticalMap['marketing'];
    verticalMap['media relations'] = verticalMap['media-relations'];
    verticalMap['finance & logistics'] = verticalMap['finance-logistics'];
    verticalMap['finance and logistics'] = verticalMap['finance-logistics'];
    verticalMap['corporate communication'] = verticalMap['corporate-communication'];
    verticalMap['corporate communications'] = verticalMap['corporate-communication'];
    verticalMap['creative designing'] = verticalMap['creative-designing'];
    verticalMap['creative & designing'] = verticalMap['creative-designing'];
    verticalMap['public relations'] = verticalMap['public-relations'];

    // 3. Create Super Admin
    const adminSalt = await bcrypt.genSalt(12);
    const adminPasswordHash = await bcrypt.hash(ENV.ADMIN_PASSWORD || 'Admin@12345', adminSalt);
    const superAdmin = await User.create({
      name: ENV.ADMIN_NAME || 'Super Admin',
      email: (ENV.ADMIN_EMAIL || 'admin@ecell.org').toLowerCase(),
      memberId: 'SUPERADMIN',
      passwordHash: adminPasswordHash,
      role: ROLES.ADMIN,
      vertical: null,
      phone: '+91 98765 43210',
      year: '4th Year',
      branch: 'Administration',
      isActive: true,
      mustChangePassword: false
    });
    console.log(` Created Super Admin: ${superAdmin.email}`);

    // Helper to determine role
    const getRole = (rec) => {
      const pos = (rec.position || '').toLowerCase();
      const name = rec.name.toLowerCase();

      // Team Representative & Vice Team Representative & R&C Lead as ADMIN
      if (pos.includes('team representative') || pos.includes('vtr') || name.includes('nikhilesh') || name.includes('rakesh') || name.includes('sri latha')) {
        return ROLES.ADMIN;
      }
      if (pos.includes('lead') && name.includes('vasanta')) {
        return ROLES.ADMIN;
      }
      if (pos.includes('lead')) {
        return ROLES.LEAD;
      }
      if (pos.includes('secretary')) {
        return ROLES.SECRETARY;
      }
      return ROLES.MEMBER;
    };

    // Helper to get vertical doc
    const getVertical = (rec) => {
      if (!rec.vertical) return null;
      const vKey = rec.vertical.toLowerCase().trim();
      return verticalMap[vKey] || null;
    };

    // 4. Create all members from PDF records
    const createdUsers = [];
    const verticalLeads = {};
    const verticalSecretaries = {};

    let seqNumber = 1;

    for (const rec of PDF_RECORDS) {
      const seqStr = String(seqNumber).padStart(3, '0');
      const memberId = `ECELL_${seqStr}`;
      seqNumber++;

      // Password: registrationnumber_ecell
      const plainPassword = `${rec.regNo.trim()}_ecell`;
      const salt = await bcrypt.genSalt(12);
      const passwordHash = await bcrypt.hash(plainPassword, salt);

      const vDoc = getVertical(rec);
      const role = getRole(rec);

      const user = await User.create({
        name: rec.name.trim(),
        email: rec.email.toLowerCase().trim(),
        memberId,
        passwordHash,
        role,
        vertical: vDoc ? vDoc._id : null,
        phone: rec.phone.trim(),
        year: rec.year.trim(),
        branch: rec.branch.trim(),
        registrationNumber: rec.regNo.trim(),
        gender: rec.gender.trim(),
        position: rec.position.trim(),
        linkedinUrl: rec.linkedin.trim(),
        residence: rec.residence.trim(),
        isActive: true,
        mustChangePassword: false,
        joinedAt: new Date(rec.timestamp ? new Date(rec.timestamp).getTime() : Date.now() - 90 * 24 * 60 * 60 * 1000)
      });

      createdUsers.push({
        memberId: user.memberId,
        name: user.name,
        email: user.email,
        phone: user.phone,
        registrationNumber: user.registrationNumber,
        password: plainPassword,
        role: user.role,
        position: user.position,
        vertical: vDoc ? vDoc.name : 'N/A'
      });

      // Track vertical leadership assignments
      if (vDoc) {
        const vSlug = vDoc.slug;
        if (!verticalLeads[vSlug]) verticalLeads[vSlug] = [];
        if (!verticalSecretaries[vSlug]) verticalSecretaries[vSlug] = [];

        if (role === ROLES.LEAD || (role === ROLES.ADMIN && rec.position.toLowerCase().includes('lead'))) {
          verticalLeads[vSlug].push(user._id);
        }
        if (role === ROLES.SECRETARY) {
          verticalSecretaries[vSlug].push(user._id);
        }
      }
    }

    // 5. Update Verticals with Assigned Leads & Secretaries
    for (const vData of DEFAULT_VERTICALS) {
      const vDoc = verticalMap[vData.slug];
      if (vDoc) {
        const leads = verticalLeads[vData.slug] || [];
        const secs = verticalSecretaries[vData.slug] || [];

        vDoc.leads = leads;
        vDoc.secretary = secs.length > 0 ? secs[0] : null;
        vDoc.secretaries = secs;
        await vDoc.save();
      }
    }

    console.log(`\n======================================================`);
    console.log(`✅ SUCCESSFULLY IMPORTED ${createdUsers.length} OFFICIAL MEMBERS TO MONGODB`);
    console.log(`- Member ID Format: ECELL_001, ECELL_002, ...`);
    console.log(`- Password Format: <RegistrationNumber>_ecell (e.g. 251FK01021_ecell)`);
    console.log(`- All student details saved: Branch, Year, Gender, Phone, Registration No, Position, LinkedIn, Residence`);
    console.log(`======================================================`);

    await mongoose.disconnect();
    return createdUsers;
  } catch (err) {
    console.error('❌ Error importing PDF members:', err);
    process.exit(1);
  }
}

if (process.argv[1].includes('importPdfMembers')) {
  importPdfMembers();
}
